routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@welcome')->name('welcome');
Route::get('/about', 'PageController@about')->name('about');

// Public Share Links
Route::get('share/{code}', 'ShortLinkController@shortenLink')->name('shorten-link');
Route::get('share/event/{event_id}/{code}', 'ShareController@shareEvent')->name("share-event");
Route::get('share/badge/{badge_id}/{code}', 'ShareController@shareBadge')->name("share-badge"); // Not Use Now
Route::get('share/ngo/{ngo_id}', 'ShareController@shareNgo')->name("share-ngo");
Route::get('share/ngo/{ngo_id}/{badge_code}', 'ShareController@shareNgoByBadgeCode')->name("share-ngo-by-badge_code");
Route::get('share/donation/{donation_id}', 'ShareController@shareDonation')->name("share-donation");
Route::get('share/donation/{donation_id}/{badge_code}', 'ShareController@shareDonationByBadgeCode')->name("share-donation-by-badge_code");


// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes... (Unwanted)
//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

Route::get('test-pdf', 'API\QuranRecitationController@testPDF');
Route::get('download-quran-recitation/{pdf_id}', 'API\QuranRecitationController@downloadQuranRecitationPDF');

Route::group(['middleware' => 'auth'], function () {

    //imi games
    Route::get('promo-games', 'CMS\IMIGamesStatsController@games')->name('imi_games.promo-games');
    Route::get('game-by-game-id', 'CMS\IMIGamesStatsController@getGameByGameUUID')->name('imi_games.game-details');

    Route::get('imi-games-reward-list', 'CMS\IMIGamesStatsController@getRewardList')->name('imi_games.reward-list');

    Route::get('game-subscription', 'CMS\IMIGamesStatsController@gameSubscriptionIndex')->name('imi_games.game-subscription-index');
    Route::get('game-unsubscription', 'CMS\IMIGamesStatsController@gameUnsubscriptionIndex')->name('imi_games.game-unsubscription-index');
    Route::get('game-revenue', 'CMS\IMIGamesStatsController@gameRevenueIndex')->name('imi_games.revenue-index');
    Route::get('game-leaderboard', 'CMS\IMIGamesStatsController@gameLeaderBoardIndex')->name('imi_games.leaderboard-index');
    Route::get('game-winners', 'CMS\IMIGamesStatsController@getWinnersData')->name('imi_games.get-winners-data');
    Route::get('game-winner-send-package', 'CMS\IMIGamesStatsController@gameWinnerSendPackage')->name('imi_games.game-winner-send-package');
    Route::post('game-winner-send-package', 'CMS\IMIGamesStatsController@gameWinnerSendPackageSubmit')->name('imi_games.game-winner-send-package');

    // Home Route
    Route::get('home', 'HomeController@home')->name('home');
    // Ads Routes
    Route::resource('ads', 'CMS\AdController');
    Route::post('ads/change-status', 'CMS\AdController@changeStatus')->name('ads.change-status');
    Route::get('ads-load-data', 'CMS\AdController@loadData')->name('ads.load-data');
    // NGO Merchants Routes
    Route::resource('ngo_merchants', 'CMS\NgoMerchantController');
    Route::post('ngo_merchants/change-status', 'CMS\NgoMerchantController@changeStatus')->name('ngo_merchants.change-status');
    Route::get('ngo_merchants-load-data', 'CMS\NgoMerchantController@loadData')->name('ngo_merchants.load-data');
    // Donations Routes
    Route::resource('donations', 'CMS\DonationController');
    Route::post('donations/change-status', 'CMS\DonationController@changeStatus')->name('donations.change-status');
    Route::get('donations-load-data', 'CMS\DonationController@loadData')->name('donations.load-data');
    // Badges Routes
    Route::resource('badges', 'CMS\BadgeController');
    Route::post('badges/change-status', 'CMS\BadgeController@changeStatus')->name('badges.change-status');
    Route::get('badges-load-data', 'CMS\BadgeController@loadData')->name('badges.load-data');
    // Event Tags Routes
    Route::resource('event_tags', 'CMS\EventTagController');
    Route::get('event_tags-load-data', 'CMS\EventTagController@loadData')->name('event_tags.load-data');
    // Events Routes
    Route::resource('events', 'CMS\EventController');
    Route::post('events/change-status', 'CMS\EventController@changeStatus')->name('events.change-status');
    Route::get('events-load-data', 'CMS\EventController@loadData')->name('events.load-data');
    // Interests Routes
    Route::resource('interests', 'CMS\InterestController');
    Route::post('interests/change-status', 'CMS\InterestController@changeStatus')->name('interests.change-status');
    Route::get('interests-load-data', 'CMS\InterestController@loadData')->name('interests.load-data');
    // Restaurants Routes
    Route::resource('restaurants', 'CMS\RestaurantController');
    Route::post('restaurants/change-status', 'CMS\RestaurantController@changeStatus')->name('restaurants.change-status');
    Route::get('restaurants-load-data', 'CMS\RestaurantController@loadData')->name('restaurants.load-data');
    // Restaurants Reviews Routes
    Route::resource('restaurant_reviews', 'CMS\RestaurantReviewController');
    Route::get('restaurant_reviews-load-data', 'CMS\RestaurantReviewController@loadData')->name('restaurant_reviews.load-data');
    // Meals Categories Routes
    Route::resource('meal_categories', 'CMS\MealCategoryController');
    Route::post('meal_categories/change-status', 'CMS\MealCategoryController@changeStatus')->name('meal_categories.change-status');
    Route::get('meal_categories-load-data', 'CMS\MealCategoryController@loadData')->name('meal_categories.load-data');
    Route::get('load-meal-categories-by-restaurant-id/{restaurant_id}', 'CMS\MealCategoryController@loadMealCategoriesByRestaurantId')->name('load-meal-categories-by-restaurant-id');
    // Meals Routes
    Route::resource('meals', 'CMS\MealController');
    Route::post('meals/change-status', 'CMS\MealController@changeStatus')->name('meals.change-status');
    Route::get('meals-load-data', 'CMS\MealController@loadData')->name('meals.load-data');
    // Meals Reviews Routes
    Route::resource('meal_reviews', 'CMS\MealReviewController');
    Route::get('meal_reviews-load-data', 'CMS\MealReviewController@loadData')->name('meal_reviews.load-data');
    // Recipes Routes
    Route::resource('recipes', 'CMS\RecipeController');
    Route::post('recipes/change-status', 'CMS\RecipeController@changeStatus')->name('recipes.change-status');
    Route::get('recipes-load-data', 'CMS\RecipeController@loadData')->name('recipes.load-data');
    // Recipes Reviews Routes
    Route::resource('recipe_reviews', 'CMS\RecipeReviewController');
    Route::get('recipe_reviews-load-data', 'CMS\RecipeReviewController@loadData')->name('recipe_reviews.load-data');
    // News Agencies Routes
    Route::resource('news_agencies', 'CMS\NewsAgencyController');
    Route::post('news_agencies/change-status', 'CMS\NewsAgencyController@changeStatus')->name('news_agencies.change-status');
    Route::get('news_agencies-load-data', 'CMS\NewsAgencyController@loadData')->name('news_agencies.load-data');
    // News Categories Routes
    Route::resource('news_categories', 'CMS\NewsCategoryController');
    Route::post('news_categories/change-status', 'CMS\NewsCategoryController@changeStatus')->name('news_categories.change-status');
    Route::get('news_categories-load-data', 'CMS\NewsCategoryController@loadData')->name('news_categories.load-data');
    // News Tags Routes
    Route::resource('news_tags', 'CMS\NewsTagController');
    Route::post('news_tags/change-status', 'CMS\NewsTagController@changeStatus')->name('news_tags.change-status');
    Route::get('news_tags-load-data', 'CMS\NewsTagController@loadData')->name('news_tags.load-data');
    // News Routes
    Route::resource('news', 'CMS\NewsController');
    Route::post('news/change-status', 'CMS\NewsController@changeStatus')->name('news.change-status');
    Route::get('news-load-data', 'CMS\NewsController@loadData')->name('news.load-data');
    // Merchants Routes
    Route::resource('merchants', 'CMS\MerchantController');
    Route::post('merchants/change-status', 'CMS\MerchantController@changeStatus')->name('merchants.change-status');
    Route::get('merchants-load-data', 'CMS\MerchantController@loadData')->name('merchants.load-data');
    // Offer Categories Routes
    Route::resource('offer_categories', 'CMS\OfferCategoryController');
    Route::post('offer_categories/change-status', 'CMS\OfferCategoryController@changeStatus')->name('offer_categories.change-status');
    Route::get('offer_categories-load-data', 'CMS\OfferCategoryController@loadData')->name('offer_categories.load-data');
    // Offers Routes
    Route::resource('offers', 'CMS\OfferController');
    Route::post('offers/change-status', 'CMS\OfferController@changeStatus')->name('offers.change-status');
    Route::get('offers-load-data', 'CMS\OfferController@loadData')->name('offers.load-data');
    // Calendar Schedule Types Routes

app/Event.php
<?php

namespace App;

use App\Helpers\APIHelper;
use App\Helpers\CMSHelper;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Event extends Model
{
    use SoftDeletes;

    protected $appends = ['status_text', 'is_user_favourite', 'share_link', 'is_my_event', 'can_invite', 'date_time', 'has_reminder'];

    protected $hidden = ['code'];

    protected $table = 'events';
    protected $fillable = ['name', 'date', 'time', 'type', 'description', 'image', 'longitude', 'latitude', 'status', 'created_at', 'updated_at'];

    public function scopeMyEvent($query)
    {
        return $query->where('created_by', APIHelper::loggedUser()->id);
    }

    public function scopePrivate($query)
    {
        return $query->where('type', 'private');
    }

    public function scopePublic($query)
    {
        return $query->where('type', 'public');
    }

    public function scopeInactive($query)
    {
        return $query->where('status', 0);
    }

    public function scopeActive($query)
    {
        return $query->where('status', 1);
    }

    public function scopePending($query)
    {
        return $query->where('status', 2);
    }

    public function scopeReject($query)
    {
        return $query->where('status', 3);
    }

    public function tag()
    {
        return $this->belongsTo('App\EventTag', 'tag_id', 'id');
    }

    public function createdUser()
    {
        return $this->belongsTo('App\User', 'created_by', 'id');
    }

    public function authorizedUser()
    {
        return $this->belongsTo('App\User', 'authorized_by', 'id');
    }

    public function favourites()
    {
        return $this->hasMany('App\UserFavouriteEvent', 'event_id', 'id')->active();
    }

    public function userFavouriteEvents()
    {
        return $this->hasMany('App\UserFavouriteEvent', 'event_id', 'id');
    }

    public function eventInvitees()
    {
        return $this->hasMany('App\EventInvitee', 'event_id', 'id');
    }

    public function invitedToMe()
    {
        return $this->hasMany('App\EventInvitee', 'event_id', 'id')->where("invitee_id", APIHelper::loggedUser()->id)->count();
    }

    public function eventMessages()
    {
        return $this->hasMany('App\EventMessage', 'event_id', 'id');
    }

    public function reminderNotifications()
    {
        return $this->hasMany('App\ReminderNotification', 'relation_id', 'id')->where('type', 'event');
    }

    public function myReminderNotification()
    {
        return $this->reminderNotifications()->where('user_id', APIHelper::loggedUser()->id);
    }

    public function getStatusTextAttribute()
    {
        return CMSHelper::getStatusText($this->attributes['status']);
    }

    public function getIsUserFavouriteAttribute()
    {
        if (APIHelper::loggedUser() !== null) {
            return $this->userFavouriteEvents()->where("user_id", APIHelper::loggedUser()->id)->count();
        } else if (auth()->user() != null) {
            return $this->userFavouriteEvents()->where("user_id", auth()->user()->id)->count();
        } else {
            return 0;
        }

    }

    public function getShareLinkAttribute()
    {
        $web_link = route("share-event", ["event_id" => $this->attributes['id'], "code" => $this->attributes['code']]);
        return APIHelper::createFirebaseShareLink($web_link);
    }

    public function getIsMyEventAttribute()
    {
        if (APIHelper::loggedUser() != null) {
            // For API
            return ($this->attributes['created_by'] == APIHelper::loggedUser()->id) || ($this->invitedToMe() > 0);
        } else if (auth()->user() != null) {
            // For CMS
            return $this->attributes['created_by'] == auth()->user()->id;
        } else {
            return false;
        }

    }

    public function getCanInviteAttribute()
    {
        if (APIHelper::loggedUser() != null) {
            // For API
            $schedule_datetime = Carbon::parse($this->attributes['date'] . " " . $this->attributes['time']);
            return ($this->attributes['created_by'] == APIHelper::loggedUser()->id) && $schedule_datetime->isFuture();
        } else if (auth()->user() != null) {
            // For CMS
            return $this->attributes['created_by'] == auth()->user()->id;
        } else {
            return false;
        }

    }

    public function unreadMessage()
    {
        $user = APIHelper::loggedUser();
        $user_id = $user->id??null;
        return $this->eventMessages()->where("from", "!=", $user_id)->where("seen",0);
    }

    public function getHasReminderAttribute()
    {
        if (APIHelper::loggedUser() != null) {
            //For API
            $reminder_count = $this->myReminderNotification()->count();
            if ($reminder_count > 0) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }

    public function getDateTimeAttribute()
    {
        return $this->attributes['date'] . " " . $this->attributes['time'];

    }

}

resources/views/pages/events/create.blade.php
@extends('layouts.app', [
    'namePage' => 'Events',
    'class' => 'sidebar-mini',
    'activePage' => 'event',
  ])

@section('content')
    <div class="panel-header panel-header-sm">
    </div>
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="pull-right">
                        <a href="{{ route('events.index') }}">
                            <button class="btn btn-dark" style="margin-right: 15px;">Back</button>
                        </a>
                    </div>
                    <div class="card-header">
                        <h4 class="card-title"> Create Event</h4>
                    </div>
                    <div class="card-body">
                        <form id="event_create" method="post" action="{{ route('events.store') }}"
                              enctype="multipart/form-data">
                            @csrf
                            @include('alerts.success')
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label for="title">{{__(" Event Name")}}</label>
                                        <input type="text" name="name" class="form-control" value="{{ old('name') }}">
                                        @include('alerts.feedback', ['field' => 'name'])
                                    </div>
                                </div>
                            </div>
                            <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
                            <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label for="title">{{__(" Date")}}</label>
                                        <input id="datepicker" name="date" class="form-control" value="{{ old('date') }}"/>
                                        <script>
                                            $('#datepicker').datepicker({ format: 'yyyy-mm-dd' });
                                        </script>
{{--                                        <input type="text" id="date" name="date" class="form-control" value="{{ old('date') }}">--}}
                                        @include('alerts.feedback', ['field' => 'date'])
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label for="title">{{__(" Time")}}</label>
                                        <input id="timepicker" name="time" class="form-control" value="{{ old('time') }}"/>
                                        <script>
                                            $('#timepicker').timepicker({format: 'HH:MM'});
                                        </script>
{{--                                        <input type="text"  id="time" name="time" class="form-control" value="{{ old('time') }}">--}}
                                        @include('alerts.feedback', ['field' => 'time'])
                                    </div>
                                </div>
                            </div>
                            {{--<div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label class="d-block" for="title">{{__(" Upload Image")}}</label>
                                        @include('includes.cropping_tool', ['id'=>1, 'name'=>'image', 'ratio'=>2, 'current_image'=>asset('assets/img/dummy.jpg'),'upload_path'=>'upload/events'])
                                        <p>Required Dimensions - Ratio 2:1 (width:height)</p>
                                        @include('alerts.feedback', ['field' => 'image_url'])
                                    </div>
                                </div>
                            </div>--}}
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label class="d-block" for="title">{{__(" Upload Image")}}</label>
                                        <img class="gal-img prev_img" id="prev_img" src="{{asset('assets/img/dummy.jpg')}}">
                                        <input type="file" class="custom-file-input" id="custom-file-input" name="image" required hidden>
                                        <p>Required Dimensions Ratio 2:1 (width:height)</p>
                                        @include('alerts.feedback', ['field' => 'image'])
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group position-relative">
                                        <div class="input-wrap position-absolute">
                                            <input type="text" id="location_name" class="form-control frm-ctrl"
                                                   placeholder="Search Box">
                                        </div>
                                        {{--Map--}}
                                        <div id="map"
                                             style="border: 2px solid #3872ac;height: 400px;width: 100%;margin: 0;padding: 0;">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label for="title">{{__(" Longitude")}}</label>
                                        <input type="text" name="longitude" id="longitude" class="form-control" value="{{ old('longitude') }}" readonly>
                                        @include('alerts.feedback', ['field' => 'longitude'])
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label for="title">{{__(" Latitude")}}</label>
                                        <input type="text" name="latitude" id="latitude" class="form-control" value="{{ old('latitude') }}" readonly>
                                        @include('alerts.feedback', ['field' => 'latitude'])
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label for="title">{{__(" Location Name")}}</label>
                                        <input type="text" name="location_name" class="form-control" value="{{ old('location_name') }}">
                                        @include('alerts.feedback', ['field' => 'location_name'])
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label for="tag">{{__(" Tag")}}</label>
                                        <select class="form-control" id="tag_id" name="tag_id" >
                                            @foreach($tags as $tag)
                                                <option value="{{$tag->id}}">{{$tag->title}}</option>
                                            @endforeach
                                        </select>
                                        @include('alerts.feedback', ['field' => 'tag_id'])
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label for="title">{{__(" Description")}}</label>
                                        <textarea type="text" name="description" class="form-control"
                                                  style="border:1px solid #E3E3E3">{{ old('description') }}</textarea>
                                        @include('alerts.feedback', ['field' => 'description'])
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer ">
                                <button type="submit" class="btn btn-primary btn-round">{{__('Create')}}</button>
                            </div>
                            <hr class="half-rule"/>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Laravel Javascript Validation -->
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
    {!! JsValidator::formRequest('App\Http\Requests\CMS\EventCreateRequest', '#event_create') !!}

    {{--############################## Google map JS Start ##########################--}}
    <script
        src="{!! url('https://maps.google.com/maps/api/js?key='.config('app.google_map_key').'&libraries=places') !!}"></script>
    <script src="{{ asset('js/locationpicker.jquery.js')}}"></script>
    <script>
        $(document).ready(function () {
            let default_latitude = 4.1754695;
            let default_longitude = 73.5093531;

            const bounds = new window.google.maps.LatLngBounds(
                new window.google.maps.LatLng(default_latitude,default_longitude),
            )

            $("#latitude").val(default_latitude);
            $("#longitude").val(default_longitude);
            $('#map').locationpicker({
                location: {
                    latitude: default_latitude,
                    longitude: default_longitude,
                },
                radius: 0,
                inputBinding: {
                    latitudeInput: $('#latitude'),
                    longitudeInput: $('#longitude'),
                    locationNameInput: $('#location_name')
                },
                enableAutocomplete: true,
                autocompleteOptions: {
                    bounds: bounds,
                },
                draggable: true,
                markerDraggable: true
            });
        });
    </script>
    {{--############################## Google map JS End ##########################--}}
@endsection

resources/views/pages/events/index.blade.php
@extends('layouts.app', [
    'namePage' => 'Events',
    'class' => 'sidebar-mini',
    'activePage' => 'event',
  ])

@section('content')
    <div class="panel-header panel-header-sm">
    </div>
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title"> Event List</h4>
                        <div class="pull-right">
                            <a href="{{ route('events.create') }}">
                                <button class="btn btn-primary">Create</button>
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table" id="events_table">
                                <thead class=" text-primary">
                                <th>ID</th>
                                <th>Image</th>
                                <th>Name</th>
                                <th>Status</th>
                                <th>Type</th>
                                <th>Date</th>
                                <th>Time</th>
                                <th>Created By</th>
                                <th>Authorized By</th>
                                <th>Published At</th>
                                <th>Action</th>
                                </thead>
                                <tbody>
                                {{--Load data--}}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        function changeStatus(item_id){
            Swal.fire({
                title: 'Change Status',
                text: "What do you want to do?",
                icon: 'warning',
                showCancelButton: true,
                showCloseButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Approve',
                cancelButtonText: 'Reject'
            }).then((result) => {
                if (result.value) {
                    // Press Approve
                    sendAjax(item_id, 1);
                } else if(result.dismiss === Swal.DismissReason.cancel) {
                    // Press Reject
                    sendAjax(item_id, 3);
                }
            })
        }

        function sendAjax(item_id, status){
            $.ajax({
                url:"{{route('events.change-status')}}",
                data:{id:item_id,status:status},
                method:"post",
                success: function (result) {
                    if(result.success){
                        Swal.fire({
                            title:'Success',
                            icon:'success',
                            text: result.message,
                        }).then((result) => {
                            location.reload();
                        });
                    } else {
                        Swal.fire({
                            title:'Error',
                            icon:'error',
                            text: result.message,
                        }).then((result) => {
                            location.reload();
                        });
                    }
                }
            });
        }

        $(document).ready(function () {

            $('#events_table').dataTable({
                "scrollY": 500,
                processing: true,
                serverSide: true,
                ajax: "{!! route('events.load-data') !!}",
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'image', name: 'image', orderable: false, searchable: false},
                    {data: 'name', name: 'name'},
                    {data: 'status_text', name: 'status_text'},
                    {data: 'type', name: 'type'},
                    {data: 'date', name: 'date'},
                    {data: 'time', name: 'time'},
                    {data: 'created_user_email', name: 'created_user_email'},
                    {data: 'authorized_user_email', name: 'authorized_user_email'},
                    {data: 'published_at', name: 'published_at'},
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ]
            });
        });

    </script>
@endsection