routes/web.php
    Route::get('game-unsubscription', 'CMS\IMIGamesStatsController@gameUnsubscriptionIndex')->name('imi_games.game-unsubscription-index');
    Route::get('game-revenue', 'CMS\IMIGamesStatsController@gameRevenueIndex')->name('imi_games.revenue-index');
    Route::get('game-leaderboard', 'CMS\IMIGamesStatsController@gameLeaderBoardIndex')->name('imi_games.leaderboard-index');
    Route::get('game-winners', 'CMS\IMIGamesStatsController@getWinnersData')->name('imi_games.get-winners-data');
    Route::get('game-winner-send-package', 'CMS\IMIGamesStatsController@gameWinnerSendPackage')->name('imi_games.game-winner-send-package');
    Route::post('game-winner-send-package', 'CMS\IMIGamesStatsController@gameWinnerSendPackageSubmit')->name('imi_games.game-winner-send-package');

    // Home Route
    Route::get('home', 'HomeController@home')->name('home');
    // Ads Routes
    Route::resource('ads', 'CMS\AdController');
    Route::post('ads/change-status', 'CMS\AdController@changeStatus')->name('ads.change-status');
    Route::get('ads-load-data', 'CMS\AdController@loadData')->name('ads.load-data');
    // NGO Merchants Routes
    Route::resource('ngo_merchants', 'CMS\NgoMerchantController');
    Route::post('ngo_merchants/change-status', 'CMS\NgoMerchantController@changeStatus')->name('ngo_merchants.change-status');
    Route::get('ngo_merchants-load-data', 'CMS\NgoMerchantController@loadData')->name('ngo_merchants.load-data');
    // Donations Routes
    Route::resource('donations', 'CMS\DonationController');
    Route::post('donations/change-status', 'CMS\DonationController@changeStatus')->name('donations.change-status');
    Route::get('donations-load-data', 'CMS\DonationController@loadData')->name('donations.load-data');
    // Badges Routes
    Route::resource('badges', 'CMS\BadgeController');
    Route::post('badges/change-status', 'CMS\BadgeController@changeStatus')->name('badges.change-status');
    Route::get('badges-load-data', 'CMS\BadgeController@loadData')->name('badges.load-data');
    // Event Tags Routes
    Route::resource('event_tags', 'CMS\EventTagController');
    Route::get('event_tags-load-data', 'CMS\EventTagController@loadData')->name('event_tags.load-data');
    // Events Routes
    Route::resource('events', 'CMS\EventController');
    Route::post('events/change-status', 'CMS\EventController@changeStatus')->name('events.change-status');
    Route::get('events-load-data', 'CMS\EventController@loadData')->name('events.load-data');
    // Interests Routes
    Route::resource('interests', 'CMS\InterestController');
    Route::post('interests/change-status', 'CMS\InterestController@changeStatus')->name('interests.change-status');
    Route::get('interests-load-data', 'CMS\InterestController@loadData')->name('interests.load-data');
    // Restaurants Routes
    Route::resource('restaurants', 'CMS\RestaurantController');
    Route::post('restaurants/change-status', 'CMS\RestaurantController@changeStatus')->name('restaurants.change-status');
    Route::get('restaurants-load-data', 'CMS\RestaurantController@loadData')->name('restaurants.load-data');
    // Restaurants Reviews Routes
    Route::resource('restaurant_reviews', 'CMS\RestaurantReviewController');
    Route::get('restaurant_reviews-load-data', 'CMS\RestaurantReviewController@loadData')->name('restaurant_reviews.load-data');
    // Meals Categories Routes
    Route::resource('meal_categories', 'CMS\MealCategoryController');
    Route::post('meal_categories/change-status', 'CMS\MealCategoryController@changeStatus')->name('meal_categories.change-status');
    Route::get('meal_categories-load-data', 'CMS\MealCategoryController@loadData')->name('meal_categories.load-data');
    Route::get('load-meal-categories-by-restaurant-id/{restaurant_id}', 'CMS\MealCategoryController@loadMealCategoriesByRestaurantId')->name('load-meal-categories-by-restaurant-id');
    // Meals Routes
    Route::resource('meals', 'CMS\MealController');
    Route::post('meals/change-status', 'CMS\MealController@changeStatus')->name('meals.change-status');
    Route::get('meals-load-data', 'CMS\MealController@loadData')->name('meals.load-data');
    // Meals Reviews Routes
    Route::resource('meal_reviews', 'CMS\MealReviewController');
    Route::get('meal_reviews-load-data', 'CMS\MealReviewController@loadData')->name('meal_reviews.load-data');
    // Recipes Routes
    Route::resource('recipes', 'CMS\RecipeController');
    Route::post('recipes/change-status', 'CMS\RecipeController@changeStatus')->name('recipes.change-status');
    Route::get('recipes-load-data', 'CMS\RecipeController@loadData')->name('recipes.load-data');
    // Recipes Reviews Routes
    Route::resource('recipe_reviews', 'CMS\RecipeReviewController');
    Route::get('recipe_reviews-load-data', 'CMS\RecipeReviewController@loadData')->name('recipe_reviews.load-data');
    // News Agencies Routes
    Route::resource('news_agencies', 'CMS\NewsAgencyController');
    Route::post('news_agencies/change-status', 'CMS\NewsAgencyController@changeStatus')->name('news_agencies.change-status');
    Route::get('news_agencies-load-data', 'CMS\NewsAgencyController@loadData')->name('news_agencies.load-data');
    // News Categories Routes
    Route::resource('news_categories', 'CMS\NewsCategoryController');
    Route::post('news_categories/change-status', 'CMS\NewsCategoryController@changeStatus')->name('news_categories.change-status');
    Route::get('news_categories-load-data', 'CMS\NewsCategoryController@loadData')->name('news_categories.load-data');
    // News Tags Routes
    Route::resource('news_tags', 'CMS\NewsTagController');
    Route::post('news_tags/change-status', 'CMS\NewsTagController@changeStatus')->name('news_tags.change-status');
    Route::get('news_tags-load-data', 'CMS\NewsTagController@loadData')->name('news_tags.load-data');
    // News Routes
    Route::resource('news', 'CMS\NewsController');
    Route::post('news/change-status', 'CMS\NewsController@changeStatus')->name('news.change-status');
    Route::get('news-load-data', 'CMS\NewsController@loadData')->name('news.load-data');
    // Merchants Routes
    Route::resource('merchants', 'CMS\MerchantController');
    Route::post('merchants/change-status', 'CMS\MerchantController@changeStatus')->name('merchants.change-status');
    Route::get('merchants-load-data', 'CMS\MerchantController@loadData')->name('merchants.load-data');
    // Offer Categories Routes
    Route::resource('offer_categories', 'CMS\OfferCategoryController');
    Route::post('offer_categories/change-status', 'CMS\OfferCategoryController@changeStatus')->name('offer_categories.change-status');
    Route::get('offer_categories-load-data', 'CMS\OfferCategoryController@loadData')->name('offer_categories.load-data');
    // Offers Routes
    Route::resource('offers', 'CMS\OfferController');
    Route::post('offers/change-status', 'CMS\OfferController@changeStatus')->name('offers.change-status');
    Route::get('offers-load-data', 'CMS\OfferController@loadData')->name('offers.load-data');
    // Calendar Schedule Types Routes
    Route::resource('calendar_schedule_types', 'CMS\CalendarScheduleTypeController');
    Route::get('calendar_schedule_types-load-data', 'CMS\CalendarScheduleTypeController@loadData')->name('calendar_schedule_types.load-data');
    // Bus Schedule Types Routes
    Route::resource('bus_schedule_types', 'CMS\BusScheduleTypeController');
    Route::get('bus_schedule_types-load-data', 'CMS\BusScheduleTypeController@loadData')->name('bus_schedule_types.load-data');
    // Bus Locations Routes
    Route::resource('bus_locations', 'CMS\BusLocationController');
    Route::get('bus_locations-load-data', 'CMS\BusLocationController@loadData')->name('bus_locations.load-data');
    // Bus Route Schedule Routes
    Route::resource('bus_route_schedules', 'CMS\BusRouteScheduleController');
    Route::get('bus_route_schedules-load-data', 'CMS\BusRouteScheduleController@loadData')->name('bus_route_schedules.load-data');
    // Bus Halt Schedule
    Route::resource('bus_halt_schedules', 'CMS\BusHaltScheduleController');
    Route::get('bus_halt_schedules-load-data', 'CMS\BusHaltScheduleController@loadData')->name('bus_halt_schedules.load-data');
    // Bus Routes Routes
    Route::resource('bus_routes', 'CMS\BusRouteController');
    Route::get('bus_routes-load-data', 'CMS\BusRouteController@loadData')->name('bus_routes.load-data');
    //Ngo Routes
    Route::resource('ngos', 'CMS\NgoController');
    Route::get('ngos-load-data', 'CMS\NgoController@loadData')->name('ngos.load-data');
    // Ferry Locations Routes
    Route::resource('ferry_locations', 'CMS\FerryLocationController');
    Route::get('ferry_locations-load-data', 'CMS\FerryLocationController@loadData')->name('ferry_locations.load-data');

    // Ferry Terminal Schedule
    Route::resource('ferry_terminal_schedules', 'CMS\FerryTerminalScheduleController');
    Route::get('ferry_terminal_schedules-load-data', 'CMS\FerryTerminalScheduleController@loadData')->name('ferry_terminal_schedules.load-data');

    // Ferry Routes Routes
    Route::resource('ferry_routes', 'CMS\FerryRouteController');
    Route::get('ferry_routes-load-data', 'CMS\FerryRouteController@loadData')->name('ferry_routes.load-data');

    // Ferry Route Schedule Routes
    Route::resource('ferry_route_schedules', 'CMS\FerryRouteScheduleController');
    Route::get('ferry_route_schedules-load-data', 'CMS\FerryRouteScheduleController@loadData')->name('ferry_route_schedules.load-data');

    // Prayer Tips Routes
    Route::resource('prayer_tips', 'CMS\PrayerTipController');
    Route::post('prayer_tips/change-status', 'CMS\PrayerTipController@changeStatus')->name('prayer_tips.change-status');
    Route::get('prayer_tips-load-data', 'CMS\PrayerTipController@loadData')->name('prayer_tips.load-data');
    // Support Teams Routes
    Route::resource('support_teams', 'CMS\SupportTeamController');

app/MealCategory.php
<?php

namespace App;

use App\Helpers\CMSHelper;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class MealCategory extends Model
{
    use SoftDeletes;

    protected $appends = ['status_text'];

    public function scopeInactive($query)
    {
        return $query->where('status', 0);
    }

    public function scopeActive($query)
    {
        return $query->where('status', 1);
    }

    public function scopePending($query)
    {
        return $query->where('status', 2);
    }

    public function scopeReject($query)
    {
        return $query->where('status', 3);
    }

    public function createdUser()
    {
        return $this->belongsTo('App\User', 'created_by', 'id');
    }

    public function meals()
    {
        return $this->hasMany('App\Meal', 'category_id', 'id');
    }

    public function restaurant()
    {
        return $this->belongsTo('App\Restaurant', 'restaurant_id', 'id');
    }

    public function merchant()
    {
        return $this->belongsTo('App\Merchant', 'merchant_id', 'id');
    }

    public function authorizedUser()
    {
        return $this->belongsTo('App\User', 'authorized_by', 'id');
    }

    public function getStatusTextAttribute()
    {
        return CMSHelper::getStatusText($this->attributes['status']);
    }
}

app/Http/Controllers/API/MealCategoryController.php
<?php

namespace App\Http\Controllers\API;

use App\Helpers\APIHelper;
use App\MealCategory;
use App\Restaurant;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class MealCategoryController extends Controller
{
    public function mealCategories(Request $request)
    {
        try {
            $meal_categories = MealCategory::active()->get();
            return APIHelper::makeAPIResponse(true, "Done", $meal_categories, 200);
        } catch (\Exception $e) {
            report($e);
            return APIHelper::makeAPIResponse(false, "Service error", null, 500);
        }
    }

    public function getMealCategoryByRestaurantId(Request $request, $restaurant_id)
    {
        try {
            $restaurant = Restaurant::find($restaurant_id);
            if ($restaurant != null) {
                $meal_category = MealCategory::with('meals')->where('restaurant_id', $restaurant_id)->active()->get();
                if ($meal_category != null) {
                    return APIHelper::makeAPIResponse(true, "Done", $meal_category, 200);
                } else {
                    return APIHelper::makeAPIResponse(false, "Meal category by restaurant not found", null, 404);
                }

            } else {
                return APIHelper::makeAPIResponse(false, "Restaurant not found", null, 404);
            }

        } catch (\Exception $e) {
            report($e);
            return APIHelper::makeAPIResponse(false, "Service error", null, 500);
        }
    }
}

resources/views/pages/meal_categories/create.blade.php
@extends('layouts.app', [
    'namePage' => 'Meal Categories',
    'class' => 'sidebar-mini',
    'activePage' => 'meal_category',
  ])

@section('content')
    <div class="panel-header panel-header-sm">
    </div>
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="pull-right">
                        <a href="{{ route('meal_categories.index') }}">
                            <button class="btn btn-dark" style="margin-right: 15px;">Back</button>
                        </a>
                    </div>
                    <div class="card-header">
                        <h4 class="card-title"> Create Meal Category</h4>
                    </div>
                    <div class="card-body">
                        <form id="meal_category_create" method="post" action="{{ route('meal_categories.store') }}" enctype="multipart/form-data">
                            @csrf
                            @include('alerts.success')
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label for="title">{{__(" Title")}}</label>
                                        <input type="text" name="title" class="form-control" value="{{ old('title') }}">
                                        @include('alerts.feedback', ['field' => 'title'])
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label for="restaurant_id">{{__(" Restaurants")}}</label>
                                        <select class="form-control" id="restaurant_id" name="restaurant_id" >
                                            @foreach($restaurants as $restaurant)
                                                <option value="{{$restaurant->id}}">{{$restaurant->title}}</option>
                                            @endforeach
                                        </select>
                                        @include('alerts.feedback', ['field' => 'restaurant_id'])
                                    </div>
                                </div>
                            </div>
                            {{--<div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label class="d-block" for="title">{{__(" Upload Image")}}</label>
                                        @include('includes.cropping_tool', ['id'=>1, 'name'=>'image', 'ratio'=>4, 'current_image'=>asset('assets/img/dummy.jpg'),'upload_path'=>'upload/meal_categories'])
                                        <p>Required Dimensions - Ratio 4:1 (width:height)</p>
                                        @include('alerts.feedback', ['field' => 'image_url'])
                                    </div>
                                </div>
                            </div>--}}
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label class="d-block" for="title">{{__(" Upload Image")}}</label>
                                        <img class="gal-img prev_img" id="prev_img" src="{{asset('assets/img/dummy.jpg')}}">
                                        <input type="file" class="custom-file-input" id="custom-file-input" name="image" required hidden>
                                        <p>Required Dimensions Ratio 4:1 (width:height)</p>
                                        @include('alerts.feedback', ['field' => 'image']  )
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer ">
                                <button type="submit" class="btn btn-primary btn-round">{{__('Create')}}</button>
                            </div>
                            <hr class="half-rule"/>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Laravel Javascript Validation -->
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
    {!! JsValidator::formRequest('App\Http\Requests\CMS\MealCategoryCreateRequest', '#meal_category_create') !!}
@endsection

resources/views/pages/meal_categories/edit.blade.php
@extends('layouts.app', [
    'namePage' => 'Meal Categories',
    'class' => 'sidebar-mini',
    'activePage' => 'meal_category',
  ])

@section('content')
    <div class="panel-header panel-header-sm">
    </div>
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="pull-right">
                        <a href="{{ route('meal_categories.index') }}">
                            <button class="btn btn-dark" style="margin-right: 15px;">Back</button>
                        </a>
                    </div>
                    <div class="card-header">
                        <h4 class="card-title"> Update Meal Category</h4>
                    </div>
                    <div class="card-body">
                        <form id="meal_category_update" method="post" action="{{ route('meal_categories.update', $meal_category->id) }}" enctype="multipart/form-data">
                            @csrf
                            @method('put')
                            @include('alerts.success')
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label for="title">{{__(" Title")}}</label>
                                        <input type="text" name="title" class="form-control" value="{{ old('title', $meal_category->title) }}">
                                        @include('alerts.feedback', ['field' => 'title'])
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label for="restaurant_id">{{__(" Restaurants")}}</label>
                                        <select class="form-control" id="restaurant_id" name="restaurant_id" >
                                            @foreach($restaurants as $restaurant)
                                                <option value="{{$restaurant->id}}"{{$restaurant->id==$meal_category->restaurant_id?"selected":""}}>{{$restaurant->title}}</option>
                                            @endforeach
                                        </select>
                                        @include('alerts.feedback', ['field' => 'restaurant_id'])
                                    </div>
                                </div>
                            </div>
                            {{--<div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label class="d-block" for="title">{{__(" Upload Image")}}</label>
                                        @include('includes.cropping_tool', ['id'=>1, 'name'=>'image', 'ratio'=>4, 'current_image'=>$meal_category->image!=null?$meal_category->image:asset('assets/img/dummy.jpg'),'upload_path'=>'upload/meal_categories'])
                                        <p>Required Dimensions - Ratio 4:1 (width:height)</p>
                                        @include('alerts.feedback', ['field' => 'image_url'])
                                    </div>
                                </div>
                            </div>--}}
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label class="d-block" for="title">{{__(" Upload Image")}}</label>
                                        <img class="gal-img prev_img" id="prev_img" src="{{$meal_category->image!=null?$meal_category->image:asset('assets/img/dummy.jpg')}}">
                                        <input type="file" class="custom-file-input" id="custom-file-input" name="image" required hidden>
                                        <p>Required Dimensions Ratio 4:1 (width:height)</p>
                                        @include('alerts.feedback', ['field' => 'image']  )
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer ">
                                <button type="submit" class="btn btn-primary btn-round">{{__('Update')}}</button>
                            </div>
                            <hr class="half-rule"/>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Laravel Javascript Validation -->
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
    {!! JsValidator::formRequest('App\Http\Requests\CMS\MealCategoryUpdateRequest', '#meal_category_update') !!}
@endsection

resources/views/pages/meal_categories/index.blade.php
@extends('layouts.app', [
    'namePage' => 'Meal Categories',
    'class' => 'sidebar-mini',
    'activePage' => 'meal_category',
  ])

@section('content')
    <div class="panel-header panel-header-sm">
    </div>
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title"> Meal Category List</h4>
                        <div class="pull-right">
                            <a href="{{ route('meal_categories.create') }}">
                                <button class="btn btn-primary">Create</button>
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table" id="meal_categories_table">
                                <thead class=" text-primary">
                                <th>ID</th>
                                <th>Image</th>
                                <th>Title</th>
                                <th>Restaurant Name</th>
                                <th>Merchant Name</th>
                                <th>Status</th>
                                <th>Created By</th>
                                <th>Published At</th>
                                <th>Created At</th>
                                <th>Action</th>
                                </thead>
                                <tbody>
                                {{--Load data--}}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        function changeStatus(item_id){
            Swal.fire({
                title: 'Change Status',
                text: "What do you want to do?",
                icon: 'warning',
                showCancelButton: true,
                showCloseButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Approve',
                cancelButtonText: 'Reject'
            }).then((result) => {
                if (result.value) {
                    // Press Approve
                    sendAjax(item_id, 1);
                } else if(result.dismiss === Swal.DismissReason.cancel) {
                    // Press Reject
                    sendAjax(item_id, 3);
                }
            })
        }

        function sendAjax(item_id, status){
            $.ajax({
                url:"{{route('meal_categories.change-status')}}",
                data:{id:item_id,status:status},
                method:"post",
                success: function (result) {
                    if(result.success){
                        Swal.fire({
                            title:'Success',
                            icon:'success',
                            text: result.message,
                        }).then((result) => {
                            location.reload();
                        });
                    } else {
                        Swal.fire({
                            title:'Error',
                            icon:'error',
                            text: result.message,
                        }).then((result) => {
                            location.reload();
                        });
                    }
                }
            });
        }

        $(document).ready(function () {

            $('#meal_categories_table').dataTable({
                "scrollY": 500,
                processing: true,
                serverSide: true,
                ajax: "{!! route('meal_categories.load-data') !!}",
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'image', name: 'image', orderable: false, searchable: false},
                    {data: 'title', name: 'title'},
                    {data: 'restaurant_id', name: 'restaurant_id'},
                    {data: 'merchant_id', name: 'merchant_id'},
                    {data: 'status_text', name: 'status_text'},
                    {data: 'created_user_email', name: 'created_user_email'},
                    {data: 'published_at', name: 'published_at'},
                    {data: 'created_at', name: 'created_at'},
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ]
            });
        });
    </script>
@endsection