routes/web.php
    Route::get('restaurants-load-data', 'CMS\RestaurantController@loadData')->name('restaurants.load-data');
    // Restaurants Reviews Routes
    Route::resource('restaurant_reviews', 'CMS\RestaurantReviewController');
    Route::get('restaurant_reviews-load-data', 'CMS\RestaurantReviewController@loadData')->name('restaurant_reviews.load-data');
    // Meals Categories Routes
    Route::resource('meal_categories', 'CMS\MealCategoryController');
    Route::post('meal_categories/change-status', 'CMS\MealCategoryController@changeStatus')->name('meal_categories.change-status');
    Route::get('meal_categories-load-data', 'CMS\MealCategoryController@loadData')->name('meal_categories.load-data');
    Route::get('load-meal-categories-by-restaurant-id/{restaurant_id}', 'CMS\MealCategoryController@loadMealCategoriesByRestaurantId')->name('load-meal-categories-by-restaurant-id');
    // Meals Routes
    Route::resource('meals', 'CMS\MealController');
    Route::post('meals/change-status', 'CMS\MealController@changeStatus')->name('meals.change-status');
    Route::get('meals-load-data', 'CMS\MealController@loadData')->name('meals.load-data');
    // Meals Reviews Routes
    Route::resource('meal_reviews', 'CMS\MealReviewController');
    Route::get('meal_reviews-load-data', 'CMS\MealReviewController@loadData')->name('meal_reviews.load-data');
    // Recipes Routes
    Route::resource('recipes', 'CMS\RecipeController');
    Route::post('recipes/change-status', 'CMS\RecipeController@changeStatus')->name('recipes.change-status');
    Route::get('recipes-load-data', 'CMS\RecipeController@loadData')->name('recipes.load-data');
    // Recipes Reviews Routes
    Route::resource('recipe_reviews', 'CMS\RecipeReviewController');
    Route::get('recipe_reviews-load-data', 'CMS\RecipeReviewController@loadData')->name('recipe_reviews.load-data');
    // News Agencies Routes
    Route::resource('news_agencies', 'CMS\NewsAgencyController');
    Route::post('news_agencies/change-status', 'CMS\NewsAgencyController@changeStatus')->name('news_agencies.change-status');
    Route::get('news_agencies-load-data', 'CMS\NewsAgencyController@loadData')->name('news_agencies.load-data');
    // News Categories Routes
    Route::resource('news_categories', 'CMS\NewsCategoryController');
    Route::post('news_categories/change-status', 'CMS\NewsCategoryController@changeStatus')->name('news_categories.change-status');
    Route::get('news_categories-load-data', 'CMS\NewsCategoryController@loadData')->name('news_categories.load-data');
    // News Tags Routes
    Route::resource('news_tags', 'CMS\NewsTagController');
    Route::post('news_tags/change-status', 'CMS\NewsTagController@changeStatus')->name('news_tags.change-status');
    Route::get('news_tags-load-data', 'CMS\NewsTagController@loadData')->name('news_tags.load-data');
    // News Routes
    Route::resource('news', 'CMS\NewsController');
    Route::post('news/change-status', 'CMS\NewsController@changeStatus')->name('news.change-status');
    Route::get('news-load-data', 'CMS\NewsController@loadData')->name('news.load-data');
    // Merchants Routes
    Route::resource('merchants', 'CMS\MerchantController');
    Route::post('merchants/change-status', 'CMS\MerchantController@changeStatus')->name('merchants.change-status');
    Route::get('merchants-load-data', 'CMS\MerchantController@loadData')->name('merchants.load-data');
    // Offer Categories Routes
    Route::resource('offer_categories', 'CMS\OfferCategoryController');
    Route::post('offer_categories/change-status', 'CMS\OfferCategoryController@changeStatus')->name('offer_categories.change-status');
    Route::get('offer_categories-load-data', 'CMS\OfferCategoryController@loadData')->name('offer_categories.load-data');
    // Offers Routes
    Route::resource('offers', 'CMS\OfferController');
    Route::post('offers/change-status', 'CMS\OfferController@changeStatus')->name('offers.change-status');
    Route::get('offers-load-data', 'CMS\OfferController@loadData')->name('offers.load-data');
    // Calendar Schedule Types Routes
    Route::resource('calendar_schedule_types', 'CMS\CalendarScheduleTypeController');
    Route::get('calendar_schedule_types-load-data', 'CMS\CalendarScheduleTypeController@loadData')->name('calendar_schedule_types.load-data');
    // Bus Schedule Types Routes
    Route::resource('bus_schedule_types', 'CMS\BusScheduleTypeController');
    Route::get('bus_schedule_types-load-data', 'CMS\BusScheduleTypeController@loadData')->name('bus_schedule_types.load-data');
    // Bus Locations Routes
    Route::resource('bus_locations', 'CMS\BusLocationController');
    Route::get('bus_locations-load-data', 'CMS\BusLocationController@loadData')->name('bus_locations.load-data');
    // Bus Route Schedule Routes
    Route::resource('bus_route_schedules', 'CMS\BusRouteScheduleController');
    Route::get('bus_route_schedules-load-data', 'CMS\BusRouteScheduleController@loadData')->name('bus_route_schedules.load-data');
    // Bus Halt Schedule
    Route::resource('bus_halt_schedules', 'CMS\BusHaltScheduleController');
    Route::get('bus_halt_schedules-load-data', 'CMS\BusHaltScheduleController@loadData')->name('bus_halt_schedules.load-data');
    // Bus Routes Routes
    Route::resource('bus_routes', 'CMS\BusRouteController');
    Route::get('bus_routes-load-data', 'CMS\BusRouteController@loadData')->name('bus_routes.load-data');
    //Ngo Routes
    Route::resource('ngos', 'CMS\NgoController');
    Route::get('ngos-load-data', 'CMS\NgoController@loadData')->name('ngos.load-data');
    // Ferry Locations Routes
    Route::resource('ferry_locations', 'CMS\FerryLocationController');
    Route::get('ferry_locations-load-data', 'CMS\FerryLocationController@loadData')->name('ferry_locations.load-data');

    // Ferry Terminal Schedule
    Route::resource('ferry_terminal_schedules', 'CMS\FerryTerminalScheduleController');
    Route::get('ferry_terminal_schedules-load-data', 'CMS\FerryTerminalScheduleController@loadData')->name('ferry_terminal_schedules.load-data');

    // Ferry Routes Routes
    Route::resource('ferry_routes', 'CMS\FerryRouteController');
    Route::get('ferry_routes-load-data', 'CMS\FerryRouteController@loadData')->name('ferry_routes.load-data');

    // Ferry Route Schedule Routes
    Route::resource('ferry_route_schedules', 'CMS\FerryRouteScheduleController');
    Route::get('ferry_route_schedules-load-data', 'CMS\FerryRouteScheduleController@loadData')->name('ferry_route_schedules.load-data');

    // Prayer Tips Routes
    Route::resource('prayer_tips', 'CMS\PrayerTipController');
    Route::post('prayer_tips/change-status', 'CMS\PrayerTipController@changeStatus')->name('prayer_tips.change-status');
    Route::get('prayer_tips-load-data', 'CMS\PrayerTipController@loadData')->name('prayer_tips.load-data');
    // Support Teams Routes
    Route::resource('support_teams', 'CMS\SupportTeamController');
    Route::post('support_teams/change-status', 'CMS\SupportTeamController@changeStatus')->name('support_teams.change-status');
    Route::get('support_teams-load-data', 'CMS\SupportTeamController@loadData')->name('support_teams.load-data');
    // Videos Routes
    Route::resource('videos', 'CMS\VideoController');
    Route::post('videos/change-status', 'CMS\VideoController@changeStatus')->name('videos.change-status');
    Route::get('videos-load-data', 'CMS\VideoController@loadData')->name('videos.load-data');
    // Users Routes
    Route::resource('users', 'CMS\UserController');
    Route::get('users-load-data', 'CMS\UserController@loadData')->name('users.load-data');
    Route::post('users-reset-password', 'CMS\UserController@resetPassword')->name('users.reset-password');
    Route::post('users-status-change', 'CMS\UserController@userStatusChange')->name('users.users-status-change');

    // Ferry Schedule
    Route::resource('ferry_schedule_types', 'CMS\FerryScheduleTypeController');
    Route::get('ferry_schedule_types-load-data', 'CMS\FerryScheduleTypeController@loadData')->name('ferry_schedule_types.load-data');

    //zakat_payments
    Route::get('zakat-payments', 'CMS\ZakatPaymentController@index')->name('zakat_payments.index');
    Route::get('zakat-payments-load-data', 'CMS\ZakatPaymentController@loadData')->name('zakat_payments.load-data');
    Route::get('zakat-payments-csv', 'CMS\ZakatPaymentController@generateCsv')->name('zakat_payments.csv');
    Route::post('zakat-payments-download-report', 'CMS\ZakatPaymentController@export')->name('zakat_payments.download-report');

    // Settings Routes
    Route::get('settings/index', 'CMS\SettingController@index')->name('settings.index');
    Route::post('settings/update', 'CMS\SettingController@update')->name('settings.update');
    Route::get('settings-load-data', 'CMS\SettingController@loadData')->name('settings.load-data');

    // Push Notifications Routes
    Route::get('push_notifications/index', 'CMS\PushNotificationController@index')->name('push_notifications.index');
    Route::post('push_notifications/update', 'CMS\PushNotificationController@update')->name('push_notifications.update');
    Route::get('push_notifications-load-data', 'CMS\PushNotificationController@loadData')->name('push_notifications.load-data');

    // Profiles
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'CMS\ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'CMS\ProfileController@update']);
    Route::post('profile-image-update', ['as' => 'profile.image.update', 'uses' => 'CMS\ProfileController@profileImageUpdate']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'CMS\ProfileController@password']);

    // Crop
    Route::post('image-cropper/upload', 'ImageCropperController@upload')->name('image_crop');


    Route::get('public_images/index', 'CMS\PublicImageController@index')->name('public_images.index');

app/Offer.php
<?php

namespace App;

use App\Helpers\CMSHelper;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Offer extends Model
{
    use SoftDeletes;

    protected $appends = ['status_text', 'content_type'];

    protected $hidden = ['is_send_push_notification', 'push_notification_status', 'push_message'];

    public function scopeInactive($query)
    {
        return $query->where('status', 0);
    }

    public function scopeActive($query)
    {
        return $query->where('status', 1);
    }

    public function scopePending($query)
    {
        return $query->where('status', 2);
    }

    public function scopeReject($query)
    {
        return $query->where('status', 3);
    }

    public function createdUser()
    {
        return $this->belongsTo('App\User', 'created_by', 'id');
    }

    public function authorizedUser()
    {
        return $this->belongsTo('App\User', 'authorized_by', 'id');
    }

    public function category()
    {
        return $this->belongsTo('App\OfferCategory', 'category_id', 'id');
    }

    public function merchant()
    {
        return $this->belongsTo('App\Merchant', 'merchant_id', 'id');
    }

    public function getStatusTextAttribute()
    {
        return CMSHelper::getStatusText($this->attributes['status']);
    }

    public function userOffers()
    {
        return $this->hasMany('App\UserOffer');
    }

    public function getContentTypeAttribute()
    {
        return "offer";
    }

}

app/Http/Controllers/API/OfferController.php
<?php

namespace App\Http\Controllers\API;

use App\Ad;
use App\Helpers\APIHelper;
use App\Http\Controllers\Controller;
use App\Offer;
use App\OfferCategory;
use App\TargetOfferUser;
use Illuminate\Http\Request;

class OfferController extends Controller
{
    public function getAllOffers(Request $request)
    {
        try {
            $offers = new Offer();
            $offers = $this->filterOfferByGenderAndAge($offers);
            $offers = $this->filterOfferByTargetOfferUsers($offers);
            return APIHelper::makeAPIResponse(true, "Done", $offers, 200);
        } catch (\Exception $e) {
            report($e);
            return APIHelper::makeAPIResponse(false, "Service error", null, 500);
        }
    }

    public function getOfferByCategoryId(Request $request, $category)
    {
        try {
            if ($category == "all") {
                $offers = new Offer();
                $offers = $this->filterOfferByGenderAndAge($offers);
                $offers = $this->filterOfferByTargetOfferUsers($offers);
                $selected_ad = Ad::offer()->active()->inRandomOrder()->first();
                if ($selected_ad != null) {
                    $selected_ad->content_type = "ad";
                    $offers = APIHelper::pushObjectToMiddleOfArray($offers, $selected_ad, 2);
                }
            } else {
                $offer_category = OfferCategory::find($category)->active()->get();
                if ($offer_category != null) {
                    $offers = new Offer();
                    $offers = $offers->where('category_id', $category);
                    $offers = $this->filterOfferByGenderAndAge($offers);
                    $offers = $this->filterOfferByTargetOfferUsers($offers);
                } else {
                    return APIHelper::makeAPIResponse(false, "Offer category not found", null, 404);
                }
            }

            return APIHelper::makeAPIResponse(true, "Done", $offers, 200);

        } catch (\Exception $e) {
            report($e);
            return APIHelper::makeAPIResponse(false, "Service error", null, 500);
        }
    }

    public function filterOfferByGenderAndAge($offers)
    {
        $user = APIHelper::loggedUser();
        if ($user->age) {
            $offers = $offers->where(function ($query) use ($user) {
                $query->where("min_age", "<=", $user->age)->orWhereNull("min_age");
            });
            $offers = $offers->where(function ($query) use ($user) {
                $query->where("max_age", ">=", $user->age)->orWhereNull("max_age");
            });
        }
        if ($user->gender == "male") {
            $offers = $offers->where("for_male", 1);
        }
        if ($user->gender == "female") {
            $offers = $offers->where("for_female", 1);
        }
        $offers = $offers->active()->latest()->get();
        return $offers;
    }

    public function filterOfferByTargetOfferUsers($offers)
    {
        $user = APIHelper::loggedUser();
        $current_user_targeted_offer_ids =  TargetOfferUser::where('user_id', $user->id)->pluck('offer_id')->toArray();
        $filtered_offers = $offers->filter(function ($value) use ($current_user_targeted_offer_ids) {
            return (!$value->is_target_offer) ||  ($value->is_target_offer && in_array($value->id, $current_user_targeted_offer_ids));
        });
        return $filtered_offers->values();
    }
}

resources/views/pages/offers/index.blade.php
@extends('layouts.app', [
    'namePage' => 'Offers',
    'class' => 'sidebar-mini',
    'activePage' => 'offer',
  ])

@section('content')
    <div class="panel-header panel-header-sm">
    </div>
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title"> Offer List</h4>
                        <div class="pull-right">
                            <a href="{{ route('offers.create') }}">
                                <button class="btn btn-primary">Create</button>
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table" id="offers_table">
                                <thead class=" text-primary">
                                <th>ID</th>
                                <th>Offer Category</th>
                                <th>Image</th>
                                <th>Title</th>
{{--                                <th>Amount</th>--}}
                                <th>Status</th>
                                <th>Created By</th>
                                <th>Authorized By</th>
                                <th>Published At</th>
                                <th>Action</th>
                                </thead>
                                <tbody>
                                {{--Load data--}}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        function changeStatus(item_id){
            Swal.fire({
                title: 'Change Status',
                text: "What do you want to do?",
                icon: 'warning',
                showCancelButton: true,
                showCloseButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Approve',
                cancelButtonText: 'Reject'
            }).then((result) => {
                if (result.value) {
                    // Press Approve
                    sendAjax(item_id, 1);
                } else if(result.dismiss === Swal.DismissReason.cancel) {
                    // Press Reject
                    sendAjax(item_id, 3);
                }
            })
        }

        function sendAjax(item_id, status){
            $.ajax({
                url:"{{route('offers.change-status')}}",
                data:{id:item_id,status:status},
                method:"post",
                success: function (result) {
                    if(result.success){
                        Swal.fire({
                            title:'Success',
                            icon:'success',
                            text: result.message,
                        }).then((result) => {
                            location.reload();
                        });
                    } else {
                        Swal.fire({
                            title:'Error',
                            icon:'error',
                            text: result.message,
                        }).then((result) => {
                            location.reload();
                        });
                    }
                }
            });
        }

        $(document).ready(function () {

            $('#offers_table').dataTable({
                "scrollY": 500,
                processing: true,
                serverSide: true,
                ajax: "{!! route('offers.load-data') !!}",
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'category_id', name: 'category_id'},
                    {data: 'image', name: 'image', orderable: false, searchable: false},
                    {data: 'title', name: 'title'},
                    //{data: 'amount', name: 'amount'},
                    {data: 'status_text', name: 'status_text'},
                    {data: 'created_user_email', name: 'created_user_email'},
                    {data: 'authorized_user_email', name: 'authorized_user_email'},
                    {data: 'published_at', name: 'published_at'},
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ]
            });
        });

    </script>
@endsection