routes/web.php
Route::group(['middleware' => 'auth'], function () {

    //imi games
    Route::get('promo-games', 'CMS\IMIGamesStatsController@games')->name('imi_games.promo-games');
    Route::get('game-by-game-id', 'CMS\IMIGamesStatsController@getGameByGameUUID')->name('imi_games.game-details');

    Route::get('imi-games-reward-list', 'CMS\IMIGamesStatsController@getRewardList')->name('imi_games.reward-list');

    Route::get('game-subscription', 'CMS\IMIGamesStatsController@gameSubscriptionIndex')->name('imi_games.game-subscription-index');
    Route::get('game-unsubscription', 'CMS\IMIGamesStatsController@gameUnsubscriptionIndex')->name('imi_games.game-unsubscription-index');
    Route::get('game-revenue', 'CMS\IMIGamesStatsController@gameRevenueIndex')->name('imi_games.revenue-index');
    Route::get('game-leaderboard', 'CMS\IMIGamesStatsController@gameLeaderBoardIndex')->name('imi_games.leaderboard-index');
    Route::get('game-winners', 'CMS\IMIGamesStatsController@getWinnersData')->name('imi_games.get-winners-data');
    Route::get('game-winner-send-package', 'CMS\IMIGamesStatsController@gameWinnerSendPackage')->name('imi_games.game-winner-send-package');
    Route::post('game-winner-send-package', 'CMS\IMIGamesStatsController@gameWinnerSendPackageSubmit')->name('imi_games.game-winner-send-package');

    // Home Route
    Route::get('home', 'HomeController@home')->name('home');
    // Ads Routes
    Route::resource('ads', 'CMS\AdController');
    Route::post('ads/change-status', 'CMS\AdController@changeStatus')->name('ads.change-status');
    Route::get('ads-load-data', 'CMS\AdController@loadData')->name('ads.load-data');
    // NGO Merchants Routes
    Route::resource('ngo_merchants', 'CMS\NgoMerchantController');
    Route::post('ngo_merchants/change-status', 'CMS\NgoMerchantController@changeStatus')->name('ngo_merchants.change-status');
    Route::get('ngo_merchants-load-data', 'CMS\NgoMerchantController@loadData')->name('ngo_merchants.load-data');
    // Donations Routes
    Route::resource('donations', 'CMS\DonationController');
    Route::post('donations/change-status', 'CMS\DonationController@changeStatus')->name('donations.change-status');
    Route::get('donations-load-data', 'CMS\DonationController@loadData')->name('donations.load-data');
    // Badges Routes
    Route::resource('badges', 'CMS\BadgeController');
    Route::post('badges/change-status', 'CMS\BadgeController@changeStatus')->name('badges.change-status');
    Route::get('badges-load-data', 'CMS\BadgeController@loadData')->name('badges.load-data');
    // Event Tags Routes
    Route::resource('event_tags', 'CMS\EventTagController');
    Route::get('event_tags-load-data', 'CMS\EventTagController@loadData')->name('event_tags.load-data');
    // Events Routes
    Route::resource('events', 'CMS\EventController');
    Route::post('events/change-status', 'CMS\EventController@changeStatus')->name('events.change-status');
    Route::get('events-load-data', 'CMS\EventController@loadData')->name('events.load-data');
    // Interests Routes
    Route::resource('interests', 'CMS\InterestController');
    Route::post('interests/change-status', 'CMS\InterestController@changeStatus')->name('interests.change-status');
    Route::get('interests-load-data', 'CMS\InterestController@loadData')->name('interests.load-data');
    // Restaurants Routes
    Route::resource('restaurants', 'CMS\RestaurantController');
    Route::post('restaurants/change-status', 'CMS\RestaurantController@changeStatus')->name('restaurants.change-status');
    Route::get('restaurants-load-data', 'CMS\RestaurantController@loadData')->name('restaurants.load-data');
    // Restaurants Reviews Routes
    Route::resource('restaurant_reviews', 'CMS\RestaurantReviewController');
    Route::get('restaurant_reviews-load-data', 'CMS\RestaurantReviewController@loadData')->name('restaurant_reviews.load-data');
    // Meals Categories Routes
    Route::resource('meal_categories', 'CMS\MealCategoryController');
    Route::post('meal_categories/change-status', 'CMS\MealCategoryController@changeStatus')->name('meal_categories.change-status');
    Route::get('meal_categories-load-data', 'CMS\MealCategoryController@loadData')->name('meal_categories.load-data');
    Route::get('load-meal-categories-by-restaurant-id/{restaurant_id}', 'CMS\MealCategoryController@loadMealCategoriesByRestaurantId')->name('load-meal-categories-by-restaurant-id');
    // Meals Routes
    Route::resource('meals', 'CMS\MealController');
    Route::post('meals/change-status', 'CMS\MealController@changeStatus')->name('meals.change-status');
    Route::get('meals-load-data', 'CMS\MealController@loadData')->name('meals.load-data');
    // Meals Reviews Routes
    Route::resource('meal_reviews', 'CMS\MealReviewController');
    Route::get('meal_reviews-load-data', 'CMS\MealReviewController@loadData')->name('meal_reviews.load-data');
    // Recipes Routes
    Route::resource('recipes', 'CMS\RecipeController');
    Route::post('recipes/change-status', 'CMS\RecipeController@changeStatus')->name('recipes.change-status');
    Route::get('recipes-load-data', 'CMS\RecipeController@loadData')->name('recipes.load-data');
    // Recipes Reviews Routes
    Route::resource('recipe_reviews', 'CMS\RecipeReviewController');
    Route::get('recipe_reviews-load-data', 'CMS\RecipeReviewController@loadData')->name('recipe_reviews.load-data');
    // News Agencies Routes
    Route::resource('news_agencies', 'CMS\NewsAgencyController');
    Route::post('news_agencies/change-status', 'CMS\NewsAgencyController@changeStatus')->name('news_agencies.change-status');
    Route::get('news_agencies-load-data', 'CMS\NewsAgencyController@loadData')->name('news_agencies.load-data');
    // News Categories Routes
    Route::resource('news_categories', 'CMS\NewsCategoryController');
    Route::post('news_categories/change-status', 'CMS\NewsCategoryController@changeStatus')->name('news_categories.change-status');
    Route::get('news_categories-load-data', 'CMS\NewsCategoryController@loadData')->name('news_categories.load-data');
    // News Tags Routes
    Route::resource('news_tags', 'CMS\NewsTagController');
    Route::post('news_tags/change-status', 'CMS\NewsTagController@changeStatus')->name('news_tags.change-status');
    Route::get('news_tags-load-data', 'CMS\NewsTagController@loadData')->name('news_tags.load-data');
    // News Routes
    Route::resource('news', 'CMS\NewsController');
    Route::post('news/change-status', 'CMS\NewsController@changeStatus')->name('news.change-status');
    Route::get('news-load-data', 'CMS\NewsController@loadData')->name('news.load-data');
    // Merchants Routes
    Route::resource('merchants', 'CMS\MerchantController');
    Route::post('merchants/change-status', 'CMS\MerchantController@changeStatus')->name('merchants.change-status');
    Route::get('merchants-load-data', 'CMS\MerchantController@loadData')->name('merchants.load-data');
    // Offer Categories Routes
    Route::resource('offer_categories', 'CMS\OfferCategoryController');
    Route::post('offer_categories/change-status', 'CMS\OfferCategoryController@changeStatus')->name('offer_categories.change-status');
    Route::get('offer_categories-load-data', 'CMS\OfferCategoryController@loadData')->name('offer_categories.load-data');
    // Offers Routes
    Route::resource('offers', 'CMS\OfferController');
    Route::post('offers/change-status', 'CMS\OfferController@changeStatus')->name('offers.change-status');
    Route::get('offers-load-data', 'CMS\OfferController@loadData')->name('offers.load-data');
    // Calendar Schedule Types Routes
    Route::resource('calendar_schedule_types', 'CMS\CalendarScheduleTypeController');
    Route::get('calendar_schedule_types-load-data', 'CMS\CalendarScheduleTypeController@loadData')->name('calendar_schedule_types.load-data');
    // Bus Schedule Types Routes
    Route::resource('bus_schedule_types', 'CMS\BusScheduleTypeController');
    Route::get('bus_schedule_types-load-data', 'CMS\BusScheduleTypeController@loadData')->name('bus_schedule_types.load-data');
    // Bus Locations Routes
    Route::resource('bus_locations', 'CMS\BusLocationController');
    Route::get('bus_locations-load-data', 'CMS\BusLocationController@loadData')->name('bus_locations.load-data');
    // Bus Route Schedule Routes
    Route::resource('bus_route_schedules', 'CMS\BusRouteScheduleController');
    Route::get('bus_route_schedules-load-data', 'CMS\BusRouteScheduleController@loadData')->name('bus_route_schedules.load-data');
    // Bus Halt Schedule
    Route::resource('bus_halt_schedules', 'CMS\BusHaltScheduleController');
    Route::get('bus_halt_schedules-load-data', 'CMS\BusHaltScheduleController@loadData')->name('bus_halt_schedules.load-data');
    // Bus Routes Routes
    Route::resource('bus_routes', 'CMS\BusRouteController');
    Route::get('bus_routes-load-data', 'CMS\BusRouteController@loadData')->name('bus_routes.load-data');
    //Ngo Routes
    Route::resource('ngos', 'CMS\NgoController');
    Route::get('ngos-load-data', 'CMS\NgoController@loadData')->name('ngos.load-data');
    // Ferry Locations Routes
    Route::resource('ferry_locations', 'CMS\FerryLocationController');
    Route::get('ferry_locations-load-data', 'CMS\FerryLocationController@loadData')->name('ferry_locations.load-data');

    // Ferry Terminal Schedule
    Route::resource('ferry_terminal_schedules', 'CMS\FerryTerminalScheduleController');
    Route::get('ferry_terminal_schedules-load-data', 'CMS\FerryTerminalScheduleController@loadData')->name('ferry_terminal_schedules.load-data');

    // Ferry Routes Routes
    Route::resource('ferry_routes', 'CMS\FerryRouteController');
    Route::get('ferry_routes-load-data', 'CMS\FerryRouteController@loadData')->name('ferry_routes.load-data');

    // Ferry Route Schedule Routes
    Route::resource('ferry_route_schedules', 'CMS\FerryRouteScheduleController');

app/Restaurant.php
<?php

namespace App;

use App\Helpers\APIHelper;
use App\Helpers\CMSHelper;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Restaurant extends Model
{
    use SoftDeletes;

    protected $appends = ['status_text', 'average_rating'];

    public function scopeInactive($query)
    {
        return $query->where('status', 0);
    }

    public function scopeActive($query)
    {
        return $query->where('status', 1);
    }

    public function scopePending($query)
    {
        return $query->where('status', 2);
    }

    public function scopeReject($query)
    {
        return $query->where('status', 3);
    }

    public function createdUser()
    {
        return $this->belongsTo('App\User', 'created_by', 'id');
    }

    public function authorizedUser()
    {
        return $this->belongsTo('App\User', 'authorized_by', 'id');
    }

    public function merchant()
    {
        return $this->belongsTo('App\Merchant', 'merchant_id', 'id');
    }

    public function getStatusTextAttribute()
    {
        return CMSHelper::getStatusText($this->attributes['status']);
    }

    public function reviews()
    {
        return $this->hasMany('App\RestaurantReview');
    }

    public function ratings()
    {
        return $this->hasMany('App\RestaurantRating');
    }

    public function getAverageRatingAttribute()
    {
        return round($this->ratings()->avg('rate'), 1);
    }

    public function myReviews()
    {
        if(APIHelper::loggedUser()!==null){
            return $this->hasMany('App\RestaurantReview')->where('created_by', APIHelper::loggedUser()->id);
        } else if(auth()->user()!=null){
            return $this->hasMany('App\RestaurantReview')->where('created_by', auth()->user()->id);
        } else {
            return 0;
        }
    }

}

resources/views/pages/restaurants/create.blade.php
@extends('layouts.app', [
    'namePage' => 'Restaurants',
    'class' => 'sidebar-mini',
    'activePage' => 'restaurant',
  ])

@section('content')
    <div class="panel-header panel-header-sm">
    </div>
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="pull-right">
                        <a href="{{ route('restaurants.index') }}">
                            <button class="btn btn-dark" style="margin-right: 15px;">Back</button>
                        </a>
                    </div>
                    <div class="card-header">
                        <h4 class="card-title"> Create Restaurant</h4>
                    </div>
                    <div class="card-body">
                        <form id="restaurant_create" method="post" action="{{ route('restaurants.store') }}"
                              enctype="multipart/form-data">
                            @csrf
                            @include('alerts.success')
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label for="title">{{__(" Restaurant Name")}}</label>
                                        <input type="text" name="title" class="form-control" value="{{ old('title') }}">
                                        @include('alerts.feedback', ['field' => 'title'])
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label for="merchant_id">{{__(" Merchants")}}</label>
                                        <select class="form-control" id="merchant_id" name="merchant_id">
                                            @if(auth()->user()->hasRole("admin"))
                                                @foreach($merchants as $merchant)
                                                    <option value="{{$merchant->id}}">{{$merchant->name}}</option>
                                                @endforeach
                                            @else
                                                @foreach(auth()->user()->merchants()->get() as $merchant)
                                                    <option
                                                        value="{{$merchant->merchant->id}}">{{$merchant->merchant->name}}
                                                    </option>
                                                @endforeach
                                            @endif
                                        </select>
                                        @include('alerts.feedback', ['field' => 'merchant_id'])
                                    </div>
                                </div>
                            </div>
                           {{-- <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label class="d-block" for="title">{{__(" Upload Image")}}</label>
                                        @include('includes.cropping_tool', ['id'=>1, 'name'=>'image', 'ratio'=>2, 'current_image'=>asset('assets/img/dummy.jpg'),'upload_path'=>'upload/restaurants'])
                                        <p>Required Dimensions - Ratio 2:1 (width:height)</p>
                                        @include('alerts.feedback', ['field' => 'image_url'])
                                    </div>
                                </div>
                            </div>--}}
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label class="d-block" for="title">{{__(" Upload Image")}}</label>
                                        <img class="gal-img prev_img" id="prev_img" src="{{asset('assets/img/dummy.jpg')}}">
                                        <input type="file" class="custom-file-input" id="custom-file-input" name="image" required hidden>
                                        <p>Required Dimensions Ratio 2:1 (width:height)</p>
                                        @include('alerts.feedback', ['field' => 'image']  )
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group position-relative">
                                        <div class="input-wrap position-absolute">
                                            <input type="text" id="location_name" class="form-control frm-ctrl"
                                                   placeholder="Search Box">
                                        </div>
                                        {{--Map--}}
                                        <div id="map"
                                             style="border: 2px solid #3872ac;height: 400px;width: 100%;margin: 0;padding: 0;">

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label for="title">{{__(" Longitude")}}</label>
                                        <input type="text" id="longitude" name="longitude" class="form-control" value="{{ old('longitude') }}" readonly>
                                        @include('alerts.feedback', ['field' => 'longitude'])
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label for="title">{{__(" Latitude")}}</label>
                                        <input type="text" id="latitude" name="latitude" class="form-control" value="{{ old('latitude') }}" readonly>
                                        @include('alerts.feedback', ['field' => 'latitude'])
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label for="title">{{__(" Location Name")}}</label>
                                        <input type="text" name="location_name" class="form-control" value="{{ old('location_name') }}">
                                        @include('alerts.feedback', ['field' => 'location_name'])
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-7 pr-1">
                                    <div class="form-group">
                                        <label for="title">{{__(" Content")}}</label>
                                        <textarea type="text" name="content" class="form-control" style="border:1px solid #E3E3E3">{{ old('content') }}</textarea>
                                        @include('alerts.feedback', ['field' => 'content'])
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer ">
                                <button type="submit" class="btn btn-primary btn-round">{{__('Create')}}</button>
                            </div>
                            <hr class="half-rule"/>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Laravel Javascript Validation -->
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
    {!! JsValidator::formRequest('App\Http\Requests\CMS\RestaurantCreateRequest', '#restaurant_create') !!}

    {{--############################## Google map JS Start ##########################--}}
    <script
        src="{!! url('https://maps.google.com/maps/api/js?key='.config('app.google_map_key').'&libraries=places') !!}"></script>
    <script src="{{ asset('js/locationpicker.jquery.js')}}"></script>
    <script>
        $(document).ready(function () {
            let default_latitude = 4.1754695;
            let default_longitude = 73.5093531;

            const bounds = new window.google.maps.LatLngBounds(
                new window.google.maps.LatLng(default_latitude,default_longitude),
            )

            $("#latitude").val(default_latitude);
            $("#longitude").val(default_longitude);
            $('#map').locationpicker({
                location: {
                    latitude: default_latitude,
                    longitude: default_longitude,
                },
                radius: 0,
                inputBinding: {
                    latitudeInput: $('#latitude'),
                    longitudeInput: $('#longitude'),
                    locationNameInput: $('#location_name')
                },
                enableAutocomplete: true,
                autocompleteOptions: {
                    bounds: bounds,
                },
                draggable: true,
                markerDraggable: true
            });
        });
    </script>
    {{--############################## Google map JS End ##########################--}}
@endsection

resources/views/pages/restaurants/index.blade.php
@extends('layouts.app', [
    'namePage' => 'Restaurants',
    'class' => 'sidebar-mini',
    'activePage' => 'restaurant',
  ])

@section('content')
    <div class="panel-header panel-header-sm">
    </div>
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title"> Restaurants List</h4>
                        <div class="pull-right">
                            <a href="{{ route('restaurants.create') }}">
                                <button class="btn btn-primary">Create</button>
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table" id="restaurants_table">
                                <thead class=" text-primary">
                                <th>ID</th>
                                <th>Image</th>
                                <th>Name</th>
                                <th>Merchant Name</th>
                                <th>Status</th>
                                <th>Location</th>
                                <th>Created By</th>
                                <th>Published At</th>
                                <th>Action</th>
                                </thead>
                                <tbody>
                                {{--Load data--}}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        function changeStatus(item_id){
            Swal.fire({
                title: 'Change Status',
                text: "What do you want to do?",
                icon: 'warning',
                showCancelButton: true,
                showCloseButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Approve',
                cancelButtonText: 'Reject'
            }).then((result) => {
                if (result.value) {
                    // Press Approve
                    sendAjax(item_id, 1);
                } else if(result.dismiss === Swal.DismissReason.cancel) {
                    // Press Reject
                    sendAjax(item_id, 3);
                }
            })
        }

        function sendAjax(item_id, status){
            $.ajax({
                url:"{{route('restaurants.change-status')}}",
                data:{id:item_id,status:status},
                method:"post",
                success: function (result) {
                    if(result.success){
                        Swal.fire({
                            title:'Success',
                            icon:'success',
                            text: result.message,
                        }).then((result) => {
                            location.reload();
                        });
                    } else {
                        Swal.fire({
                            title:'Error',
                            icon:'error',
                            text: result.message,
                        }).then((result) => {
                            location.reload();
                        });
                    }
                }
            });
        }

        $(document).ready(function () {

            $('#restaurants_table').dataTable({
                "scrollY": 500,
                processing: true,
                serverSide: true,
                ajax: "{!! route('restaurants.load-data') !!}",
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'image', name: 'image', orderable: false, searchable: false},
                    {data: 'title', name: 'title'},
                    {data: 'merchant_id', name: 'merchant_id'},
                    {data: 'status_text', name: 'status_text'},
                    {data: 'location_name', name: 'location_name'},
                    {data: 'created_user_email', name: 'created_user_email'},
                    {data: 'published_at', name: 'published_at'},
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ]
            });
        });
    </script>
@endsection